using System;
using System.Collections.Generic;
using UnityEngine;

namespace KDT.GraspTraining
{
    /// <summary>
    /// Fixed policy shape and stable whole-hand grasp task contract.
    /// </summary>
    public static class Dg5fGraspSpec
    {
        public const string SpecVersion = "3.0.0";
        public const string BehaviorName = "DG5FStableGrasp";
        public const int ObservationSize = 116;
        public const int ActionSize = 26;
        public const int ArmJointCount = 6;
        public const int HandJointCount = 20;
        public const int FingerCount = 5;
        public const int HandActionOffset = ArmJointCount;
        public const float MaximumHandDeltaDegPerDecision = 4f;
        public const string CurriculumParameterName = "stable_grasp_stage";
        public const int FirstCurriculumStage = 1;
        public const int FinalCurriculumStage = 3;
        public const float PreGraspFraction = 0.35f;

        public const float EpisodeTimeoutSeconds = 20f;
        public const float DecisionTimePenalty = -0.001f;
        public const float ApproachPotentialMaximum = 1f;
        public const float ApproachRewardScale = 0.25f;
        public const float ApproachSuccessDistance = 0.05f;

        public const int ThumbFingerIndex = 0;
        public const int FirstOpposingFingerIndex = 1;
        public const int RequiredNonThumbContactCount = 2;
        public const float PerFingerContactPotential = 0.1f;
        public const float ContactPotentialMaximum = 0.5f;
        public const float RequiredContactHoldSeconds = 0.5f;
        public const float StableGraspAcquiredReward = 0.5f;

        public const float StageTwoLiftHeight = 0.02f;
        public const float FinalLiftHeight = 0.05f;
        public const float FinalMinimumHoldHeight = 0.04f;
        public const float MaximumStableLinearSpeed = 0.05f;
        public const float StageTwoStableHoldSeconds = 0.5f;
        public const float FinalStableHoldSeconds = 1f;
        public const float LiftPotentialMaximum = 1f;
        public const float StableHoldPotentialMaximum = 1f;
        public const float StableGraspSuccessReward = 3f;

        public const float V1MinimumSpawnRadius = 0.35f;
        public const float V1MaximumSpawnRadius = 0.70f;
        public const float SupportTopHeight = 0f;
        public const float PanelWidth = 1.80f;
        public const float PanelDepth = 1.80f;
        public const float PanelThickness = 0.25f;
        public const float MaximumSpawnBallDistance = 0.80f;
        public const float MaximumBallDistance = 0.85f;
        public const float GraspBallRadius = 0.02f;

        public static readonly string[] ArmLinks =
        {
            "shoulder_link", "upper_arm_link", "forearm_link",
            "wrist_1_link", "wrist_2_link", "wrist_3_link"
        };

        public static readonly float[] ArmSafeMinDeg =
        {
            -180f, -120f, 20f, -180f, -150f, -180f
        };

        public static readonly float[] ArmSafeMaxDeg =
        {
            180f, -20f, 140f, 0f, -30f, 180f
        };

        // Channel order: finger 1..5, joint 1..4.
        public static readonly float[] PreGrasp35Deg =
        {
            -14f, 28f, -21f, -21f,
              0f, 35f, 28f, 24.5f,
              0f, 35f, 28f, 24.5f,
              0f, 33.25f, 28f, 24.5f,
              0f, 0f, 28f, 24.5f
        };

        // Generated by GraspPointCalibrator from the source prefab preview.
        public static readonly Vector3 CalibratedGraspPointLocalPosition =
            new Vector3(0.0170203224f, 0.152462155f, 0.0135399457f);

        public static int HandActionIndex(int handJointIndex)
        {
            if (handJointIndex < 0 || handJointIndex >= HandJointCount)
                throw new ArgumentOutOfRangeException(nameof(handJointIndex));
            return HandActionOffset + handJointIndex;
        }

        public static Vector3 EqualWeightedCenter(IReadOnlyList<Vector3> positions)
        {
            if (positions == null) throw new ArgumentNullException(nameof(positions));
            if (positions.Count != FingerCount)
                throw new ArgumentException($"Expected {FingerCount} fingertip positions.", nameof(positions));

            Vector3 center = Vector3.zero;
            for (int index = 0; index < positions.Count; index++)
            {
                if (!IsFinite(positions[index]))
                    throw new ArgumentException("Fingertip positions must be finite.", nameof(positions));
                center += positions[index];
            }
            return center / positions.Count;
        }

        public static Vector3 PalmLocalGraspPoint(Transform palm, IReadOnlyList<Transform> fingerTips)
        {
            if (palm == null) throw new ArgumentNullException(nameof(palm));
            if (fingerTips == null) throw new ArgumentNullException(nameof(fingerTips));
            if (fingerTips.Count != FingerCount)
                throw new ArgumentException($"Expected {FingerCount} fingertips.", nameof(fingerTips));

            var positions = new Vector3[FingerCount];
            for (int index = 0; index < positions.Length; index++)
            {
                if (fingerTips[index] == null)
                    throw new ArgumentException($"Fingertip {index} is null.", nameof(fingerTips));
                positions[index] = fingerTips[index].position;
            }
            return palm.InverseTransformPoint(EqualWeightedCenter(positions));
        }

        public static float AccumulateJointTarget(
            float currentTargetDeg,
            float normalizedAction,
            float maximumDeltaDeg,
            float lowerLimitDeg,
            float upperLimitDeg)
        {
            if (!IsFinite(currentTargetDeg) || !IsFinite(normalizedAction)
                || !IsFinite(maximumDeltaDeg))
            {
                return ClampJointTarget(0f, lowerLimitDeg, upperLimitDeg);
            }
            float delta = Mathf.Clamp(normalizedAction, -1f, 1f)
                * Mathf.Max(0f, maximumDeltaDeg);
            return ClampJointTarget(currentTargetDeg + delta, lowerLimitDeg, upperLimitDeg);
        }

        public static float ClampJointTarget(float valueDeg, float lowerLimitDeg, float upperLimitDeg)
        {
            if (!IsFinite(valueDeg) || !IsFinite(lowerLimitDeg) || !IsFinite(upperLimitDeg))
                return 0f;
            return Mathf.Clamp(
                valueDeg,
                Mathf.Min(lowerLimitDeg, upperLimitDeg),
                Mathf.Max(lowerLimitDeg, upperLimitDeg));
        }

        public static float NormalizeJoint(float valueDeg, float lowerDeg, float upperDeg)
        {
            if (upperDeg <= lowerDeg) return 0f;
            return Mathf.Clamp((valueDeg - lowerDeg) / (upperDeg - lowerDeg) * 2f - 1f, -1f, 1f);
        }

        public static float ApproachPotential(float graspDistance)
        {
            if (!IsFinite(graspDistance)) return 0f;
            return ApproachPotentialMaximum
                * (1f - Mathf.Clamp01(Mathf.Max(0f, graspDistance) / MaximumBallDistance));
        }

        public static float PotentialDelta(float previousPotential, float currentPotential)
        {
            if (!IsFinite(previousPotential) || !IsFinite(currentPotential)) return 0f;
            return currentPotential - previousPotential;
        }

        public static int ContactFingerCount(bool[] fingerContacts)
        {
            if (fingerContacts == null || fingerContacts.Length != FingerCount) return 0;
            int count = 0;
            for (int index = 0; index < FingerCount; index++)
                if (fingerContacts[index]) count++;
            return count;
        }

        public static int NonThumbContactCount(bool[] fingerContacts)
        {
            if (fingerContacts == null || fingerContacts.Length != FingerCount) return 0;
            int count = 0;
            for (int index = FirstOpposingFingerIndex; index < FingerCount; index++)
                if (fingerContacts[index]) count++;
            return count;
        }

        public static bool HasThumbContact(bool[] fingerContacts)
        {
            return fingerContacts != null
                && fingerContacts.Length == FingerCount
                && fingerContacts[ThumbFingerIndex];
        }

        public static bool HasStableContact(bool[] fingerContacts)
        {
            return HasThumbContact(fingerContacts)
                && NonThumbContactCount(fingerContacts) >= RequiredNonThumbContactCount;
        }

        public static float ContactPotential(bool[] fingerContacts)
        {
            if (!HasThumbContact(fingerContacts)) return 0f;
            return Mathf.Min(
                ContactPotentialMaximum,
                PerFingerContactPotential * (1 + NonThumbContactCount(fingerContacts)));
        }

        public static float NextContactHoldSeconds(
            float previousContactHoldSeconds,
            bool hasStableContact,
            float deltaSeconds)
        {
            if (!hasStableContact) return 0f;
            if (!IsFinite(previousContactHoldSeconds) || !IsFinite(deltaSeconds)) return 0f;
            return Mathf.Max(0f, previousContactHoldSeconds) + Mathf.Max(0f, deltaSeconds);
        }

        public static bool HasAcquiredStableGrasp(float contactHoldSeconds)
        {
            return IsFinite(contactHoldSeconds)
                && contactHoldSeconds >= RequiredContactHoldSeconds - 1e-6f;
        }

        public static float StableContactProgress(float contactHoldSeconds, bool stableGraspAcquired)
        {
            if (stableGraspAcquired) return 1f;
            if (!IsFinite(contactHoldSeconds)) return 0f;
            return Mathf.Clamp01(Mathf.Max(0f, contactHoldSeconds) / RequiredContactHoldSeconds);
        }

        public static float RequiredLiftHeight(int curriculumStage)
        {
            if (curriculumStage <= FirstCurriculumStage) return 0f;
            return curriculumStage < FinalCurriculumStage
                ? StageTwoLiftHeight
                : FinalLiftHeight;
        }

        public static float MinimumHoldHeight(int curriculumStage)
        {
            if (curriculumStage <= FirstCurriculumStage) return 0f;
            return curriculumStage < FinalCurriculumStage
                ? StageTwoLiftHeight
                : FinalMinimumHoldHeight;
        }

        public static float RequiredStableHoldSeconds(int curriculumStage)
        {
            if (curriculumStage <= FirstCurriculumStage) return 0f;
            return curriculumStage < FinalCurriculumStage
                ? StageTwoStableHoldSeconds
                : FinalStableHoldSeconds;
        }

        public static float LiftHeight(float currentBallHeight, float initialBallHeight)
        {
            if (!IsFinite(currentBallHeight) || !IsFinite(initialBallHeight)) return 0f;
            return Mathf.Max(0f, currentBallHeight - initialBallHeight);
        }

        public static float LiftPotential(
            float liftHeight,
            float requiredLiftHeight,
            bool stableGraspAcquired)
        {
            if (!stableGraspAcquired || !IsFinite(liftHeight) || !IsFinite(requiredLiftHeight)
                || requiredLiftHeight <= 0f)
            {
                return 0f;
            }
            return LiftPotentialMaximum
                * Mathf.Clamp01(Mathf.Max(0f, liftHeight) / requiredLiftHeight);
        }

        public static bool HasReachedLiftTarget(float liftHeight, float requiredLiftHeight)
        {
            return IsFinite(liftHeight)
                && IsFinite(requiredLiftHeight)
                && liftHeight >= requiredLiftHeight - 1e-6f;
        }

        public static float NextStableHoldSeconds(
            float previousHoldSeconds,
            bool hasStableContact,
            bool liftTargetReached,
            float liftHeight,
            float minimumHoldHeight,
            float linearSpeed,
            float deltaSeconds)
        {
            bool valid = hasStableContact
                && liftTargetReached
                && IsFinite(liftHeight)
                && IsFinite(minimumHoldHeight)
                && IsFinite(linearSpeed)
                && liftHeight >= minimumHoldHeight - 1e-6f
                && linearSpeed <= MaximumStableLinearSpeed + 1e-6f;
            if (!valid) return 0f;
            if (!IsFinite(previousHoldSeconds) || !IsFinite(deltaSeconds)) return 0f;
            return Mathf.Max(0f, previousHoldSeconds) + Mathf.Max(0f, deltaSeconds);
        }

        public static float StableHoldPotential(float stableHoldSeconds, float requiredHoldSeconds)
        {
            if (!IsFinite(stableHoldSeconds) || !IsFinite(requiredHoldSeconds)
                || requiredHoldSeconds <= 0f)
            {
                return 0f;
            }
            return StableHoldPotentialMaximum
                * Mathf.Clamp01(Mathf.Max(0f, stableHoldSeconds) / requiredHoldSeconds);
        }

        public static bool HasCompletedStableHold(float stableHoldSeconds, float requiredHoldSeconds)
        {
            return IsFinite(stableHoldSeconds)
                && IsFinite(requiredHoldSeconds)
                && requiredHoldSeconds > 0f
                && stableHoldSeconds >= requiredHoldSeconds - 1e-6f;
        }

        public static float FailurePotentialSettlement(
            float approachPotential,
            float contactPotential,
            float liftPotential,
            float holdPotential)
        {
            return ApproachRewardScale * PotentialDelta(approachPotential, 0f)
                + PotentialDelta(contactPotential, 0f)
                + PotentialDelta(liftPotential, 0f)
                + PotentialDelta(holdPotential, 0f);
        }

        public static float FailurePenalty(string failureReason)
        {
            switch (failureReason)
            {
                case "Timeout":
                    return -0.1f;
                case "GripLost":
                case "Drop":
                    return -0.5f;
                case "WorkspaceExit":
                case "NonFinitePhysics":
                    return -1f;
                default:
                    return 0f;
            }
        }

        public static bool HasReachedApproachTarget(float graspDistance)
        {
            return IsFinite(graspDistance)
                && graspDistance <= ApproachSuccessDistance + 1e-6f;
        }

        public static float AreaUniformRadius(float unitSample)
        {
            float minimumSquared = V1MinimumSpawnRadius * V1MinimumSpawnRadius;
            float maximumSquared = V1MaximumSpawnRadius * V1MaximumSpawnRadius;
            return Mathf.Sqrt(Mathf.Lerp(
                minimumSquared,
                maximumSquared,
                Mathf.Clamp01(unitSample)));
        }

        public static Vector3 SpawnBallLocalPosition(
            float radiusUnitSample,
            float azimuthUnitSample,
            float ballRadius)
        {
            float horizontalRadius = AreaUniformRadius(radiusUnitSample);
            float azimuth = Mathf.Clamp01(azimuthUnitSample) * 2f * Mathf.PI;
            return new Vector3(
                Mathf.Cos(azimuth) * horizontalRadius,
                SupportTopHeight + Mathf.Max(0f, ballRadius),
                Mathf.Sin(azimuth) * horizontalRadius);
        }

        public static bool IsValidSpawn(Vector3 ballLocalPosition, float ballRadius)
        {
            if (!IsFinite(ballLocalPosition)) return false;
            float horizontalRadius = new Vector2(ballLocalPosition.x, ballLocalPosition.z).magnitude;
            float nonNegativeBallRadius = Mathf.Max(0f, ballRadius);
            float pedestalTopHeight = ballLocalPosition.y - nonNegativeBallRadius;
            return horizontalRadius >= V1MinimumSpawnRadius - 1e-6f
                && horizontalRadius <= V1MaximumSpawnRadius + 1e-6f
                && Mathf.Abs(ballLocalPosition.x) + nonNegativeBallRadius <= PanelWidth * 0.5f
                && Mathf.Abs(ballLocalPosition.z) + nonNegativeBallRadius <= PanelDepth * 0.5f
                && Mathf.Approximately(pedestalTopHeight, SupportTopHeight)
                && ballLocalPosition.magnitude <= MaximumSpawnBallDistance;
        }

        public static bool ReachedEpisodeTimeout(float elapsedSeconds)
        {
            return IsFinite(elapsedSeconds)
                && elapsedSeconds >= EpisodeTimeoutSeconds - 1e-5f;
        }

        public static string BallFailureReason(Vector3 ballLocalPosition, float supportTopHeight)
        {
            if (!IsFinite(ballLocalPosition)) return "NonFinitePhysics";
            if (ballLocalPosition.magnitude > MaximumBallDistance) return "WorkspaceExit";
            if (ballLocalPosition.y < supportTopHeight) return "Drop";
            return null;
        }

        public static bool IsFinite(float value)
        {
            return !float.IsNaN(value) && !float.IsInfinity(value);
        }

        public static bool IsFinite(Vector3 value)
        {
            return IsFinite(value.x) && IsFinite(value.y) && IsFinite(value.z);
        }
    }
}
